### ISSUE TITLE
zmiany do zrobienia

### ISSUE THREAD

**Issue by zdolny** [sbojdo/if-else-statement#1]
1. Dodaj doctype do html
2. Twoj skrypt zwraca bledne wyniki - wybrobuj chociazby dla liczb 2 i 1. Dzieje sie tak dlatego, ze a^2 w js nie podnosi do kwadratu tylko wykonuje operacje XOR na bitach (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators)
3. Nie do konca mozesz zalozyc, ze jesli cos nie jest liczba dodatnia, ani ujemna to jest zerem. Proponuje osobny warunek do sprawdzenia, czy licza jest faktycznie zerem, a potem cala reszta bedzie wynikiem nieokreslonym. Teraz jak podam pusta liczbe, lub litere to dostaje jakis wynik, ktory jest nieprawdziwy

(zmiany poprosze w osobny branchu + pull request)

**Comment by sbojdo** [comment]
poprawione na branchu fewChanges
